services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: tx_manager_postgres
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    restart: always
    container_name: tx_manager_redis
    ports:
      - 6379:6379

  scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile.scheduler
    image: scheduler # Name the image
    container_name: tx_manager_scheduler
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://root:password@postgres:5432/main
    depends_on:
      - postgres
      - redis
    restart: always

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    image: tx_manager # Name the image
    container_name: tx_manager_app
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://root:password@postgres:5432/main
    depends_on:
      - postgres
      - redis
      - scheduler
    ports:
      - 3000:3000
    restart: always
