FROM node:20-alpine
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY ./scheduler ./
COPY ./server ./server
COPY ./drizzle/schema.ts ./drizzle/
COPY ./tsconfig.json ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

EXPOSE 3000

CMD [ "pnpm", "start" ]
